### ISSUE TITLE
User id 1001 is wrong

### ISSUE THREAD

**Issue by montyz** [bitnami/bitnami-docker-wildfly#71]
**Description**

**Steps to reproduce the issue:**

1. `whoami` -> `whoami: cannot find name for user ID 1001`
2. `cat /etc/passwd` -> ends with `bitnami:x:1000:1000::/home/bitnami:/bin/bash`
3. Inspect DOCKERFILE -> USER 1001

**Version**

This is for `bitnami/wildfly:19.0.0` but from what I can tell it is still an issue.

**Comment by alemorcuq** [comment]
That's something expected. This container is compatible with arbitrary UIDs, which means you can run the container using any UID you want, e.g.:

    $ docker run --user 1234 bitnami/wordpress

This is very important to be compatible with some K8s platforms such as Openshift, since these platforms use random UIDs to deploy the containers by default. Since we cannot assume the UID of the user that will be running the container, we cannot add it to the `/etc/passwd`. 

With this approach we are also adding some consistency to our containers: it does not matter the user you are running the container as, you will always see the same.

**Comment by montyz** [comment]
Oh, thanks for the explanation. I do get errors if I try to run with the bitnami user, is that expected too? Ultimately I'm trying to get `jstat` to work. With user 1001 `jstat` fails complaining that it cannot find user 1001.

Closing since this is not actually a bug.
